name: Build Cloud Lab LaTeX document
on:
  - pull_request
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cloudlab.tex
          args: '-pdf -file-line-error -interaction=nonstopmode -shell-escape'
